# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c9192a3f4d05e13e50a79713a46f97d5d2f975efee7f34e4af9bed3435b0f5cbbde31c9d9edd05adda1294eb5a3e8f7716468e002d1cc610212274cc71960e3c

test:
  secret_key_base: 19354af48ac0ca892d34b7338994dcd0a6ef33f163ec52a7590a7794ff0992fb2ac1f38d1898080034ab8f7fb94366f4048216ca79dd1e6c72ac3e028397f383

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
